const products = [
    {
        name: "cotton t-shirt",
        price: 37,
        quantity: 8,
        favourite: false,
        colour: ["red", "blue", "green"],
        size: ["small", "medium", "large"],
        image: "/img",
    },
    {
        name: "band t-shirt",
        price: 66,
        quantity: 17,
        favourite: false,
        colour: ["red", "black", "white"],
        size: ["small", "medium", "large"],
        image: "/img",
    },
    {
        name: "hoodie",
        price: 52,
        quantity: 12,
        favourite: false,
        colour: ["red", "blue", "purple"],
        size: ["small", "medium", "large"],
        image: "/img",
    },
    {
        name: "jeans",
        price: 40,
        quantity: 26,
        favourite: false,
        colour: ["black", "blue"],
        size: ["small", "medium", "large"],
        image: "/img",
    },
    {
        name: "sweatpants",
        price: 29,
        quantity: 13,
        favourite: false,
        colour: ["black", "grey", "white"],
        size: ["small", "medium", "large"],
        image: "/img",
    },
    {
        name: "scarf",
        price: 24,
        quantity: 1,
        favourite: false,
        colour: ["red", "blue", "green"],
        size: ["none"],
        image: "/img",
    },
    {
        name: "short skirt",
        price: 42,
        quantity: 12,
        favourite: false,
        colour: ["red", "blue", "green"],
        size: ["small", "medium", "large"],
        image: "/img",
    },
    {
        name: "long skirt",
        price: 54,
        quantity: 7,
        favourite: false,
        colour: ["red", "blue", "green"],
        size: ["small", "medium", "large"],
        image: "/img",
    },
    {
        name: "floral dress",
        price: 56,
        quantity: 27,
        favourite: false,
        colour: ["red", "blue", "green"],
        size: ["small", "medium", "large"],
        image: "/img",
    },
    {
        name: "runners",
        price: 35,
        quantity: 6,
        favourite: false,
        colour: ["red", "blue", "orange"],
        size: ["8", "9", "10", "11", "12"],
        image: "/img",
    },
    {
        name: "sneakers",
        price: 30,
        quantity: 11,
        favourite: false,
        colour: ["red", "black", "brown"],
        size: ["8", "9", "10", "11", "12"],
        image: "/img",
    },
    {
        name: "sandals",
        price: 21,
        quantity: 12,
        favourite: false,
        colour: ["black", "brown"],
        size: ["8", "9", "10", "11", "12"],
        image: "/img",
    },
    {
        name: "jacket",
        price: 38,
        quantity: 21,
        favourite: false,
        colour: ["red", "blue", "green"],
        size: ["small", "medium", "large"],
        image: "/img",
    },
    {
        name: "gloves",
        price: 15,
        quantity: 10,
        favourite: false,
        colour: ["red", "blue", "green"],
        size: ["small", "medium", "large"],
        image: "/img",
    },
    {
        name: "shorts",
        price: 22,
        quantity: 12,
        favourite: false,
        colour: ["black", "blue", "brown"],
        size: ["small", "medium", "large"],
        image: "/img",
    },
    {
        name: "baseball cap",
        price: 13,
        quantity: 11,
        favourite: false,
        colour: ["red", "blue", "green"],
        size: ["small", "medium", "large"],
        image: "/img",
    },
    {
        name: "wide-brim hat",
        price: 12,
        quantity: 2,
        favourite: false,
        colour: ["red", "blue", "green"],
        size: ["small", "medium", "large"],
        image: "/img",
    },
    {
        name: "coat",
        price: 55,
        quantity: 5,
        favourite: false,
        colour: ["red", "blue", "green"],
        size: ["small", "medium", "large"],
        image: "/img",
    },
    {
        name: "sunglasses",
        price: 10,
        quantity: 12,
        favourite: false,
        colour: ["red", "blue", "green"],
        size: ["none"],
        image: "/img",
    },
    {
        name: "belt",
        price: 5,
        quantity: 14,
        favourite: false,
        colour: ["none"],
        size: ["small", "medium", "large"],
        image: "/img",
    },
];

export default products;
